# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/heorhij/Linux_Unreal_Engine_5.5.4

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	GroupFiveProject-Android-DebugGame  \
	GroupFiveProject-Android-Development  \
	GroupFiveProject-Android-Shipping  \
	GroupFiveProject-Linux-DebugGame  \
	GroupFiveProject-Linux-Development  \
	GroupFiveProject-Linux-Shipping  \
	GroupFiveProject-LinuxArm64-DebugGame  \
	GroupFiveProject-LinuxArm64-Development  \
	GroupFiveProject-LinuxArm64-Shipping  \
	GroupFiveProject \
	GroupFiveProjectEditor-Linux-DebugGame  \
	GroupFiveProjectEditor-Linux-Development  \
	GroupFiveProjectEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend GroupFiveProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug GroupFiveProjectEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

GroupFiveProject-Android-DebugGame:
	 $(BUILD) GroupFiveProject Android DebugGame  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-Android-Development:
	 $(BUILD) GroupFiveProject Android Development  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-Android-Shipping:
	 $(BUILD) GroupFiveProject Android Shipping  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-Linux-DebugGame:
	 $(BUILD) GroupFiveProject Linux DebugGame  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-Linux-Development:
	 $(BUILD) GroupFiveProject Linux Development  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-Linux-Shipping:
	 $(BUILD) GroupFiveProject Linux Shipping  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-LinuxArm64-DebugGame:
	 $(BUILD) GroupFiveProject LinuxArm64 DebugGame  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-LinuxArm64-Development:
	 $(BUILD) GroupFiveProject LinuxArm64 Development  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject-LinuxArm64-Shipping:
	 $(BUILD) GroupFiveProject LinuxArm64 Shipping  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProject: GroupFiveProject-Linux-Development

GroupFiveProjectEditor-Linux-DebugGame:
	 $(BUILD) GroupFiveProjectEditor Linux DebugGame  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProjectEditor-Linux-Development:
	 $(BUILD) GroupFiveProjectEditor Linux Development  -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" $(ARGS)

GroupFiveProjectEditor: GroupFiveProjectEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/heorhij/Дакументы/Unreal Projects/GroupFiveProject/GroupFiveProject.uproject" -Game 

.PHONY: $(TARGETS)
